# Generated by Django 5.1.2 on 2024-10-16 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_manager', '0007_alter_historicaltipocarga_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('rut', models.CharField(max_length=255, null=True)),
                ('dig_v', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Agencia de transporte',
                'verbose_name_plural': 'Agencias de transporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aceptacion', models.DateField(null=True)),
                ('aduana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aduana', to='collection_manager.aduana')),
                ('agencia_transporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agencia_transporte', to='interpreter.agenciatransporte')),
                ('puerto_desembarque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puerto_desembarque', to='collection_manager.puerto')),
                ('puerto_embarque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puerto_embarque', to='collection_manager.puerto')),
                ('tipo_carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carga', to='collection_manager.tipocarga', to_field='codigo')),
            ],
            options={
                'verbose_name': 'Registro de embarque',
                'verbose_name_plural': 'Registros de embarque',
                'ordering': ['puerto_embarque', 'puerto_desembarque'],
            },
        ),
    ]
