# Generated by Django 5.1.2 on 2024-10-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0007_alter_historicaltipocarga_codigo_and_more'),
        ('interpreter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nro_manifiesto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='num_registro',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMO', models.IntegerField(null=True)),
                ('MMSI', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('fecha_construccion', models.DateField(null=True)),
                ('bandera', models.CharField(max_length=255, null=True)),
                ('callsign', models.CharField(max_length=255, null=True)),
                ('draft', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('deadweight', models.IntegerField(null=True)),
                ('historial', models.TextField(null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_manager.pais')),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='nave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nave', to='interpreter.nave'),
        ),
    ]
