# Generated by Django 5.1.2 on 2024-10-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0002_registro_nro_manifiesto_registro_num_registro_nave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='nro_manifiesto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
