# Generated by Django 5.1.2 on 2024-10-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0003_alter_registro_nro_manifiesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['num_registro', 'puerto_embarque', 'puerto_desembarque'], 'verbose_name': 'Registro Importación/Exportación', 'verbose_name_plural': 'Registros Importación/Exportación'},
        ),
    ]
