# Generated by Django 5.1.2 on 2024-10-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0002_alter_historicalpuerto_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodalidadventa',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modalidadventa',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
