# Generated by Django 5.1.2 on 2024-10-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0004_historicalsector_sector_historicalpuerto_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsector',
            name='region',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='region',
        ),
        migrations.AddField(
            model_name='historicalsector',
            name='cd_reparticion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalsector',
            name='sitport_nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsector',
            name='sitport_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='cd_reparticion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='sitport_nom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='sitport_valor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsector',
            name='id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsector',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
