# Generated by Django 5.1.2 on 2024-10-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0006_alter_aduana_latitud_alter_aduana_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltipocarga',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tipocarga',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
