# Generated by Django 5.1.3 on 2024-11-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0007_alter_historicaltipocarga_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpuerto',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puerto',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
