# Generated by Django 5.1.3 on 2024-11-14 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0008_historicalpuerto_important_puerto_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpuerto',
            name='zona_geografica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_manager.sector'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='zona_geografica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
