# Generated by Django 5.1.3 on 2024-11-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0010_historicalruta_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpuerto',
            name='eslora_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='eslora_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
