# Generated by Django 5.1.3 on 2024-11-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_manager', '0013_historicalpuerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpuerto',
            name='tipos_cargas',
            field=models.CharField(blank=True, choices=[('GR', 'Granel'), ('CO', 'Contenedor'), ('LI', 'Líquido'), ('RE', 'Refrigerado'), ('OT', 'Otro')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='puerto',
            name='tipos_cargas',
            field=models.CharField(blank=True, choices=[('GR', 'Granel'), ('CO', 'Contenedor'), ('LI', 'Líquido'), ('RE', 'Refrigerado'), ('OT', 'Otro')], default=None, max_length=2, null=True),
        ),
    ]
