# Generated by Django 5.1.2 on 2024-10-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero1', models.IntegerField()),
                ('numero2', models.IntegerField()),
                ('resultado', models.IntegerField()),
            ],
        ),
    ]
